version: "3.9"

services:
  authentication:
    build:
      context: ./authenticationMicroservice
    ports:
      - "5050:5050"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=ecoDrive_authentication_db
    depends_on:
      - database
    networks:
      - ecoDriveNetwork
    restart: always

  payment:
    build:
      context: ./paymentMicroservice
    ports:
      - "5200:5200"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=ecoDrive_payment_db
    depends_on:
      - database
    networks:
      - ecoDriveNetwork
    restart: always

  user:
    build:
      context: ./userMicroservice
    ports:
      - "5100:5100"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=ecoDrive_user_db
    depends_on:
      - database
    networks:
      - ecoDriveNetwork
    restart: always

  vehicle:
    build:
      context: ./vehicleMicroservice
    ports:
      - "5150:5150"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=ecoDrive_vehicle_db
    depends_on:
      - database
    networks:
      - ecoDriveNetwork
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - ecoDriveNetwork
    restart: always

  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3308:3306" # Use host port 3308 to avoid conflicts with local MySQL
    volumes:
      - ./database:/docker-entrypoint-initdb.d # Custom SQL scripts for database initialization
      - db_data:/var/lib/mysql # Persistent storage for MySQL data
    networks:
      - ecoDriveNetwork
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pexample"]
      interval: 10s
      retries: 5
      start_period: 30s # Increased start period for MySQL initialization
    restart: always

volumes:
  db_data: # Persistent storage for MySQL data

networks:
  ecoDriveNetwork:
    driver: bridge
